# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-27 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0019_auto_20160915_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='opening_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
