# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0020_auto_20171027_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='opening_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[(b'Chairman', b'Chairman'), (b'Secretary', b'Secretary'), (b'Treasurer', b'Treasurer')], max_length=20),
        ),
    ]
