# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0021_auto_20171029_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[(b'Chairmanr', b'Chairman'), (b'Secretary', b'Secretary'), (b'Treasure', b'Treasurer')], max_length=20),
        ),
    ]
